language: python
python:
 - "3.6"
before_install:
 - 'pip install -U pip'
cache: pip
install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
env:
 - FLASK_VERSION=1.0.2
 - FLASK_APP='run.py'
 - FLASK_ENV='development'
 - APP_SETTINGS='development'
 - development_url='dbname=storemanager_db user=user_1 password=test123 host=localhost port=5432'
 - testing_url='dbname=test_db user=user_1 password=test123 host=localhost port=5432'
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres  
  - psql -c "create user user_1 WITH PASSWORD 'test123';" -U postgres
  - cp .env.example .env
script: 
 - pytest --cov-report term-missing --cov app -v 
after_success:
 - coveralls
 - codeclimate-test-reporter